repos:
  - repo: https://github.com/psf/black
    rev: 21.10b0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/PyCQA/flake8
    rev: "4.0.1"
    hooks:
      - id: flake8
  - repo: https://github.com/timothycrosley/isort
    rev: "5.10.1"
    hooks:
      - id: isort
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
      - id: bandit
        args: ["--ini=.bandit", "--recursive", "-a=file"]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.4.1"
    hooks:
      - id: prettier
        args: [ '--config=.prettierrc.js' ]
        files: ^.*\.(ts|tsx|js|css|html|json)$
