version: "3.8"
services:

  backend:
    build:
      context: .
      dockerfile: ./projects/backend/Dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV:-true}
      target: dev
    entrypoint: "bash -c "
    command:
      - "uvicorn app.main:app --reload --host 0.0.0.0 --port 8888"
    volumes:
      - ./projects/backend/:/code


  frontend:
    build:
      context: .
      dockerfile: ./projects/frontend/Dockerfile
      args:
        NODE_ENV: dev
      target: dev
    command: "npm start"
    volumes:
      - ./projects/frontend/:/code
    ports:
      - "3000:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`localhost`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"