version: "3.8"
services:

  proxy:
    image: "traefik:v2.5"
    container_name: "traefik"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./projects/traefik/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      # - "./projects/traefik/traefik.dev.toml:/etc/traefik/traefik.toml"

  backend:
    build:
      context: .
      dockerfile: ./projects/backend/Dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV:-true}
      target: dev
    entrypoint: "./docker-entrypoint.sh"
    command: "api"
    volumes:
      - ./projects/backend/:/code


  frontend:
    build:
      context: .
      dockerfile: ./projects/frontend/Dockerfile
      args:
        NODE_ENV: dev
      target: dev
    command: "npm start"
    volumes:
      - ./projects/frontend/:/code
    ports:
      - "3000:3000"